### ISSUE TITLE
Scroll to bottom behaviour

### ISSUE THREAD

**Issue by maehr** [digihistch24/book-of-abstracts#39]
### Current Behavior

When scrolling to the bottom of the page the layout is not aligned anymore

![Screenshot 2024-08-21 at 10 48 55](https://github.com/user-attachments/assets/c64568d3-7820-4cc2-98e7-b117711deb9e)

**Comment by mtwente** [comment]
@maehr You are referring to the white-ish scroll bar, aren't you?

**Comment by maehr** [comment]
Yes, exactly
